services:
  recommender:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "0.0.0.0:50051:50051"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
