# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation/v1/recommendation.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'recommendation/v1/recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&recommendation/v1/recommendation.proto\x12\x11recommendation.v1\"-\n\x10RecommendRequest\x12\x19\n\x08item_ids\x18\x01 \x03(\x05R\x07itemIds\".\n\x11RecommendResponse\x12\x19\n\x08item_ids\x18\x01 \x03(\x05R\x07itemIds2l\n\x12RecommenderService\x12V\n\tRecommend\x12#.recommendation.v1.RecommendRequest\x1a$.recommendation.v1.RecommendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation.v1.recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDREQUEST']._serialized_start=61
  _globals['_RECOMMENDREQUEST']._serialized_end=106
  _globals['_RECOMMENDRESPONSE']._serialized_start=108
  _globals['_RECOMMENDRESPONSE']._serialized_end=154
  _globals['_RECOMMENDERSERVICE']._serialized_start=156
  _globals['_RECOMMENDERSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
